[package]
name = "quote-client"
version = "0.1.0"
edition = "2024"

[dependencies]
quote-streaming = { path = "../quote-streaming" }
clap = { workspace = true }
ctrlc = { workspace = true }
thiserror = { workspace = true }
rancor = { workspace = true }
