[package]
name = "quote-client"
version = "0.1.0"
edition = "2024"

[dependencies]
rkyv = { workspace = true }
quote-streaming = { path = "../quote-streaming" }
rancor = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true }
