[workspace]
resolver = "2"
members = ["quote-client","quote-server", "quote-streaming"]

[workspace.dependencies]
rkyv = "0.8"
rancor = "0.1"
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
ctrlc = "3"
thiserror = "2"
